apiVersion: apps/v1
kind: Deployment
metadata:
  name: garageworker
  labels:
    app: garageworker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: garageworker
  template:
    metadata:
      labels:
        app: garageworker
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
    spec:
      volumes:
        - name: garageworker-storage
          persistentVolumeClaim:
            claimName: garageworker-claim
      containers:
      - name: garageworker
        image: registry:5000/garageworker:latest
        imagePullPolicy: Always
        envFrom:
        - secretRef: 
            name: garageworker-secret
        - configMapRef:
            name: garageworker-configmap
        ports:
        - containerPort: 80
          name: http
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          timeoutSeconds: 30
        resources:
          requests:
            memory: "128Mi"
            cpu: "16m"
          limits:
            memory: "256Mi"
            cpu: "512m"
        volumeMounts:
          - mountPath: "/data"
            name: garageworker-storage
---
