apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: garageworker-secret
  namespace: garage
spec:
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: garageworker-secret
      namespace: garage

